#!/bin/bash

set -e

cd /opt/

## Download Eclipse from the eclipse servers
wget -c https://ftp.fau.de/eclipse/technology/epp/downloads/release/oxygen/1/eclipse-java-oxygen-1-linux-gtk-x86_64.tar.gz

##DEBHELPER##
